name: Build docker image and push to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build-n-push:
    if: github.repository_owner == 'dptech-corp'
    name: Build docker image and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: read version
      id: read
      uses: juliangruber/read-file-action@v1
      with:
        path: ./VERSION

    - name: Build and push
      run: |
        docker build --platform linux/arm64,linux/amd64 -t dptechnology/dflow:v${{ steps.read.outputs.content }} --push .
        docker build --platform linux/arm64,linux/amd64 -t dptechnology/dflow:latest --push .

  send-email:
    if: github.repository_owner == 'dptech-corp'
    name: send email to inform developers
    runs-on: ubuntu-latest
    needs: [ build-n-push ]
    steps:
    - name: read version
      id: read
      uses: juliangruber/read-file-action@v1
      with:
        path: ./VERSION
    - name: send email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.feishu.cn
        server_port: 465
        username: ${{ secrets.MAILUSERNAME }}
        password: ${{ secrets.MAILPASSWORD }}
        subject: PyPI Auto Build For Dflow
        body: dptechnology/dflow:v${{ steps.read.outputs.content }}
        to: ${{ secrets.MAIL_RECEIVER_LIST }}
        from: Github Actions
        content_type: text
